const Exchanges_Properties = [
  {
    name: "CandleChart_day",
    ref: "CandleChart_day",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
  {
    name: "CandleChart_week",
    ref: "CandleChart_week",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
  {
    name: "CandleChart_month",
    ref: "CandleChart_month",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
  {
    name: "CandleChart_year",
    ref: "CandleChart_year",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
  {
    name: "Liquidation",
    ref: "Liquidation",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
  {
    name: "OpenInterestVolumeFutures",
    ref: "OpenInterestVolumeFutures",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
  {
    name: "OpenInterestVolumeHistory_1min",
    ref: "OpenInterestVolumeHistory_1min",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
  {
    name: "OpenInterestVolumeHistory_5min",
    ref: "OpenInterestVolumeHistory_5min",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
  {
    name: "OpenInterestVolumeHistory_15min",
    ref: "OpenInterestVolumeHistory_15min",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
  {
    name: "OpenInterestVolumeHistory_1hr",
    ref: "OpenInterestVolumeHistory_1hr",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
  {
    name: "OpenInterestVolumeHistory_4hr",
    ref: "OpenInterestVolumeHistory_4hr",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
  {
    name: "OpenInterestVolumeHistory_12hr",
    ref: "OpenInterestVolumeHistory_12hr",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
  {
    name: "OpenInterestVolumeHistory_24hr",
    ref: "OpenInterestVolumeHistory_24hr",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
  {
    name: "Spot",
    ref: "Spot",
    localField: "_id",
    foreignField: "exchange",
    justOne: false,
  },
];

module.exports = Exchanges_Properties;
