//Common Region
export const SET_THEME_OPPOSITE = "SET_THEME_OPPOSITE";
// End Of Common Region

// Alert Region
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
// End Of Alert Region

// Auth Region
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOG_OUT = "LOG_OUT";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_FAIL = "VERIFICATION_FAIL";
export const VERIFICATION_FAIL_VIA_LINK = "VERIFICATION_FAIL_VIA_LINK";
export const SET_SHOW_VERIFY_MODAL_TRUE = "SET_SHOW_VERIFY_MODAL_TRUE";
export const SET_VERIFICATION_LOADING_TRUE = "SET_VERIFICATION_LOADING_TRUE";
export const SET_VERIFICATION_LOADING_FALSE = "SET_VERIFICATION_LOADING_FALSE";

export const RESEND_VERIFICATION_SUCCESS = "RESEND_VERIFICATION_SUCCESS";
export const RESEND_VERIFICATION_FAIL = "RESEND_VERIFICATION_FAIL";
export const SET_SHOW_FORGOT_PASSWORD_MODAL_TRUE =
  "SET_SHOW_FORGOT_PASSWORD_MODAL_TRUE";
export const SET_SHOW_FORGOT_PASSWORD_MODAL_FALSE =
  "SET_SHOW_FORGOT_PASSWORD_MODAL_FALSE";
export const SET_SHOW_RESET_PASSWORD_MODAL_TRUE =
  "SET_SHOW_RESET_PASSWORD_MODAL_TRUE";
export const SET_SHOW_RESET_PASSWORD_MODAL_FALSE =
  "SET_SHOW_RESET_PASSWORD_MODAL_FALSE";
export const FORGOT_PASSWORD_SEND_SUCCESS = "FORGOT_PASSWORD_SEND_SUCCESS";
export const RESET_PASSWORD_SEND_SUCCESS = "RESET_PASSWORD_SEND_SUCCESS";
// End of Auth Region

//Uploads Region
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_LOADING = "UPLOAD_LOADING";
//End Of Uploads Region

//MapBox map region
export const SEARCH_CITIES = "SEARCH_CITIES ";
export const GET_HEAT_POINTS_SUCCESS = "GET_HEAT_POINTS_SUCCESS ";
export const GET_HEAT_POINTS_LOADING = "GET_HEAT_POINTS_LOADING ";
export const SELECT_FILTER_DATE = "SELECT_FILTER_DATE ";
export const SELECT_FILTER_TYPE = "SELECT_FILTER_TYPE ";
//End of MapBox map region

//Sensor Region
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_SENSOR_DETAILS_SUCCESS = "GET_SENSOR_DETAILS_SUCCESS";
//End Of Sensor Region

//Weather
export const UPDATE_WEATHER_DATA = "UPDATE_WEATHER_DATA ";
