// Alert Region
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// End of Alert Region

// Auth Region
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOG_OUT = 'LOG_OUT';
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAIL = 'VERIFICATION_FAIL';
export const VERIFICATION_FAIL_VIA_LINK = 'VERIFICATION_FAIL_VIA_LINK';
export const SET_SHOW_VERIFY_MODAL_TRUE = 'SET_SHOW_VERIFY_MODAL_TRUE';
export const SET_VERIFICATION_LOADING_TRUE = 'SET_VERIFICATION_LOADING_TRUE';
export const SET_VERIFICATION_LOADING_FALSE = 'SET_VERIFICATION_LOADING_FALSE';

export const RESEND_VERIFICATION_SUCCESS = 'RESEND_VERIFICATION_SUCCESS';
export const RESEND_VERIFICATION_FAIL = 'RESEND_VERIFICATION_FAIL';
export const SET_SHOW_FORGOT_PASSWORD_MODAL_TRUE =
  'SET_SHOW_FORGOT_PASSWORD_MODAL_TRUE';
export const SET_SHOW_FORGOT_PASSWORD_MODAL_FALSE =
  'SET_SHOW_FORGOT_PASSWORD_MODAL_FALSE';
export const SET_SHOW_RESET_PASSWORD_MODAL_TRUE =
  'SET_SHOW_RESET_PASSWORD_MODAL_TRUE';
export const SET_SHOW_RESET_PASSWORD_MODAL_FALSE =
  'SET_SHOW_RESET_PASSWORD_MODAL_FALSE';
export const FORGOT_PASSWORD_SEND_SUCCESS = 'FORGOT_PASSWORD_SEND_SUCCESS';
export const RESET_PASSWORD_SEND_SUCCESS = 'RESET_PASSWORD_SEND_SUCCESS';
// End of Auth Region

//CoinEvents region
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE';
export const GET_COINEVENTCARDS_SUCCESS = 'GET_COINEVENTCARDS_SUCCESS';
export const GET_COINS_SUCCESS = 'GET_COINS_SUCCESS';
export const SET_COINS_LOADING_TRUE = 'SET_COINS_LOADING_TRUE';
export const SET_COINS_LOADING_FALSE = 'SET_COINS_LOADING_FALSE';
export const GET_FILTERED_COINS_SUCCESS = 'GET_FILTERED_COINS_SUCCESS';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_FILTERED_COINEVENTCARDS_SUCCESS =
  'GET_FILTERED_COINEVENTCARDS_SUCCESS';
export const CHECK_NEXTPAGE_COINEVENTS = 'CHECK_NEXTPAGE_COINEVENTS';

// Coin Region
export const GET_COIN_SUCCESS = 'GET_COIN_SUCCESS';
// End of Coin Region

// Exchanges Region
export const GET_EXCHANGE_SUCCESS = 'GET_EXCHANGE_SUCCESS';
// End of Exchanges Region

//Websokets region
export const GET_WEBSOCKET_SUCCESS = 'GET_SPOT_SUCCESS';
export const GET_COINDATA_SUCCESS = 'GET_COINDATA_SUCCESS';
export const GET_EXCHANGEDATA_SUCCESS = 'GET_EXCHANGEDATA_SUCCESS';
export const GET_FUTUREEXCHANGEDATA_SUCCESS = 'GET_FUTUREEXCHANGEDATA_SUCCESS';
export const GET_PERPETUALEXCHANGEDATA_SUCCESS =
  'GET_PERPETUALEXCHANGEDATA_SUCCESS';
export const LOADING_TRUE = 'LOADING_TRUE';
export const GET_MARKETDATACHANGE_SUCCESS = 'GET_MARKETDATACHANGE_SUCCESS';
export const SET_WEBSOCKETDATALIST_NULL = 'SET_WEBSOCKETDATALIST_NULL';

// End of Websokets Region

// Graph Region
export const GET_FUTURESDATA_SUCCESS = 'GET_FUTURESDATA_SUCCESS';
export const GET_PERPETUALDATA_SUCCESS = 'GET_PERPETUALDATA_SUCCESS';
export const GET_OIVOLUMEDATA_SUCCESS = 'GET_OIVOLUMEDATA_SUCCESS';
export const GET_SHORTLONG_SUCCESS = 'GET_SHORTLONG_SUCCESS';
export const FUTURE_PERPETUAL_LOADING_SUCCES =
  'FUTURE_PERPETUAL_LOADING_SUCCES';
export const GRAPH_THREE_LOADING_SUCCES = 'GRAPH_THREE_LOADING_SUCCES';
export const GET_LIQUIDATION_LOADING_SUCCES = 'GET_LIQUIDATION_LOADING_SUCCES';
export const GRAPH_FOUR_LOADING_SUCCES = 'GRAPH_FOUR_LOADING_SUCCES';
export const GRAPH_SIX_LOADING_SUCCES = 'GRAPH_SIX_LOADING_SUCCES';
export const GET_SEEALL_BUTTON_STATE_SUCCESS =
  'GET_SEEALL_BUTTON_STATE_SUCCESS';
// End Of Graph Region

// Spot Graph Region
export const GET_SINGLECOINDATA_SUCCESS = 'GET_SINGLECOINDATA_SUCCESS';
export const GET_PAIRDATA_SUCCESS = 'GET_PAIRDATA_SUCCESS';
export const GET_EXCHANGESTATE_SUCCESS = 'GET_EXCHANGESTATE_SUCCESS';
// End Of Spot Graph Region
('GET_FILTERED_COINEVENTCARDS_SUCCESS');
//End of CoinEvents region

//Welcome page sub sections region
export const GET_WELCOME_COINEVENTS_SUCCESS = 'GET_WELCOME_COINEVENTS_SUCCESS';
export const GET_WELCOME_CRYPTONEWS_SUCCESS = 'GET_WELCOME_CRYPTONEWS_SUCCESS';
export const GET_WELCOME_SOCIALFEEDS_SUCCESS =
  'GET_WELCOME_SOCIALFEEDS_SUCCESS';
export const SHOW_LEARNMOREABOUT365 = 'SHOW_LEARNMOREABOUT365';
export const HIDE_LEARNMOREABOUT365 = 'HIDE_LEARNMOREABOUT365';
export const SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS';
export const SUBSCRIPTION_SUCCESS_FALSE = 'SUBSCRIPTION_SUCCESS_FALSE';
export const GET_FITEREDCOINS_MARKETDATA = ' GET_FITEREDCOINS_MARKETDATA';
export const SET_FILTERED_COINS_NULL = ' SET_FILTERED_COINS_NULL';
export const UNSUBSCRIPTION_SUCCESS = ' UNSUBSCRIPTION_SUCCESS';
//End of welcome page sub sections region

//Strapi region
export const GET_STRAPIDATA_SUCCUES = 'GET_STRAPIDATA_SUCCUES';
export const GET_ARTICLEDATA_SUCCUES = 'GET_ARTICLEDATA_SUCCUES';
export const GET_STRAPIHUB_BANNER_SUCCUES = 'GET_STRAPIHUB_BANNER_SUCCUES';
//End of Strapi region

//CryptoNews region
export const SET_CRYPTONEWS_LOADING_TRUE = 'SET_CRYPTONEWS_LOADING_TRUE';
export const SET_CRYPTONEWS_LOADING_FALSE = 'SET_CRYPTONEWS_LOADING_FALSE';
export const GET_CRYPTONEWS_SUCCESS = 'GET_CRYPTONEWS_SUCCESS';
export const GET_CRYPTONEWS_COINS_SUCCESS = 'GET_CRYPTONEWS_COINS_SUCCESS';
export const GET_CRYPTONEWS_FILTERED_COINS_SUCCESS =
  'GET_CRYPTONEWS_FILTERED_COINS_SUCCESS';
export const GET_FILTERED_CRYPTONEWS_SUCCESS =
  'GET_FILTERED_CRYPTONEWS_SUCCESS';
export const SET_CRYPTONEWS_COINS_LOADING_TRUE =
  'SET_CRYPTONEWS_COINS_LOADING_TRUE';
export const SET_CRYPTONEWS_COINS_LOADING_FALSE =
  'SET_CRYPTONEWS_COINS_LOADING_FALSE';
export const SET_SELECTED_SENTIMENT = 'SET_SELECTED_SENTIMENT';
//---sentiment chart
export const GET_SENTIMENTCHARTDATA_SUCCESS = 'GET_SENTIMENTCHARTDATA_SUCCESS';
export const GET_FILTERED_SENTIMENTCHARTDATA_SUCCESS =
  'GET_FILTERED_SENTIMENTCHARTDATA_SUCCESS';
export const SET_SENTIMENTCHARTDATA_LOADING_TRUE =
  'SET_SENTIMENTCHARTDATA_LOADING_TRUE';
export const SET_SENTIMENTCHARTDATA_LOADING_FALSE =
  'SET_SENTIMENTCHARTDATA_LOADING_FALSE';
export const CHECK_NEXTPAGE_CRYPTONEWS = 'CHECK_NEXTPAGE_CRYPTONEWS';

//End of CryptoNews region

//SocialFeeds region
export const SET_SOCIALFEEDS_LOADING_TRUE = 'SET_SOCIALFEEDS_LOADING_TRUE';
export const SET_SOCIALFEEDS_LOADING_FALSE = 'SET_SOCIALFEEDS_LOADING_FALSE';
export const GET_SOCIALFEEDS_SUCCESS = 'GET_SOCIALFEEDS_SUCCESS';
export const GET_SOCIALFEEDS_COINSLIST_SUCCESS =
  'GET_SOCIALFEEDS_COINSLIST_SUCCESS';
export const SET_SOCIALFEEDS_COINSLIST_LOADING_TRUE =
  'SET_SOCIALFEEDS_COINSLIST_LOADING_TRUE';
export const SET_SOCIALFEEDS_COINSLIST_LOADING_FALSE =
  'SET_SOCIALFEEDS_COINSLIST_LOADING_FALSE';
export const GET_SOCIALFEEDS_FILTERED_COINSLIST_SUCCESS =
  'GET_SOCIALFEEDS_FILTERED_COINSLIST_SUCCESS';
export const GET_FILTERED_SOCIALFEEDS_SUCCESS =
  'GET_FILTERED_SOCIALFEEDS_SUCCESS';
export const CHECK_NEXTPAGE_SOCIALFEEDS = 'CHECK_NEXTPAGE_SOCIALFEEDS';
//End of SocialFeeds region

//issue report region
export const REPORT_ISSUE_SUCCESS = 'REPORT_ISSUE_SUCCESS';
export const GET_SUCCESS_FALSE = 'GET_SUCCESS_FALSE';
//End of issue report region

//my account region
export const CHANGE_USER_DETAILS_SUCCESS = 'CHANGE_USER_DETAILS_SUCCESS';
export const CHANGE_USER_PASSWORD_SUCCESS = 'CHANGE_USER_PASSWORD_SUCCESS';
export const CHANGE_USER_SUBSCRIPTION_SUCCESS =
  'CHANGE_USER_SUBSCRIPTION_SUCCESS';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_TICKBOX_SUCCESS = 'GET_TICKBOX_SUCCESS';
export const GET_SECTION_SUCCESS = 'GET_SECTION_SUCCESS';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const SHOW_SUBSCRIPTION_MESSAGE_MODAL =
  'SHOW_SUBSCRIPTION_MESSAGE_MODAL';
export const HIDE_SUBSCRIPTION_MESSAGE_MODAL =
  'HIDE_SUBSCRIPTION_MESSAGE_MODAL';
//End of my account region
